### ISSUE TITLE
"No RSP devices available."

### ISSUE THREAD

**Issue by ssemkaz** [DkCocto/kSDR#1]
![image](https://user-images.githubusercontent.com/84036865/216786098-a296c8b5-5f35-463f-9050-75039eaf693a.png)

**Comment by DkCocto** [comment]
Hello!

Very glad to hear feedback from you!

Can you, please, tell me which SDR device you are using?

Do you have RSP1 or RSP1A devices in use including their Chinese clones
from the aliexpress store?

Denis.

сб, 4 февр. 2023 г. в 22:28, ssemkaz ***@***.***>:

**Comment by DkCocto** [comment]
If you have an sdr device rsp1/rsp1a or their clones, then in order to run our application you need to install v2 drivers (API 2.13).

Link to download drivers:
https://www.sdrplay.com/dlfinishs/

Filename: SDRplay_RSP_API-Windows-2.13.1.exe

If you previously had v3. So they must be removed first.

**Comment by DkCocto** [comment]
At the moment, the beta version 2 includes the ability to customize the application for your device. See the description of the "config.xml" file. There you can select an available device and api version to work with it.
