### ISSUE TITLE
Линукс?

### ISSUE THREAD

**Issue by Cvarc-Xtal** [DkCocto/kSDR#3]
Добрый день. Отличный проект. Спасибо.
Не планируете версию под линукс?

**Comment by DkCocto** [comment]
Здравствуйте!
Спасибо за обратную связь! В сущности под линукс переделать не сложно. Пока что программой пользуются, на сколько мне известно, немного людей. В большей мере у всех windows. Переделал бы все под линукс, если приложение станет популярнее) 
Хотелось бы услышать от вас небольшой отзыв. Мнение и впечатления.
